<a href="https://colab.research.google.com/github/KIRANRW9/Numpy/blob/repo-exercise/NumpyD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NumPy***

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

1.**Creating Arrays** of 1D,2D and 3D.






In [39]:
import numpy as np
#1D Array
a=np.array([1,2,3])
print(a)

print("----------------------------------------------------")
#2D Array
b=np.array([[1.9,2,3],[4,5,6]],dtype=float)
print(b)

print("----------------------------------------------------")
#3D Arrray
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],dtype=float)
print(c)

[1 2 3]
----------------------------------------------------
[[1.9 2.  3. ]
 [4.  5.  6. ]]
----------------------------------------------------
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]]


Initial Placeholders

2.This creates 3X4 Array filled with 0.

In [40]:
a=np.zeros((3,4))
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3.This creates 3D array (5 Blocks of 3X4) filled with ones using integer type.

In [41]:
b=np.ones((5,3,4),dtype=np.int16)
print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


3.Array with step value
# Starts at 10 and goes upto 25 but 25 in not include.

In [42]:
c=np.arange(10,25,2)
print(c)

[10 12 14 16 18 20 22 24]


4.Array with equal intervals
It divides the 1-50 into 5 equal parts

In [43]:
d=np.linspace(1,50,5)
print(d)

[ 1.   13.25 25.5  37.75 50.  ]


5.Constant Matrix it creates a 3X5 matrix with full of 7.

In [44]:
e=np.full((3,5),7)
print(e)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


6.It creates a 5X5 Identity Matrix (1's on Diagonl 0's else where

In [45]:
f=np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


7.Random values from 0 to 1 float values of 4X5 matrix

In [46]:
g=np.random.random((4,5))
print(g)

[[0.63633371 0.51290748 0.36793501 0.36795989 0.93161158]
 [0.14788312 0.7503091  0.33444246 0.27089031 0.80369293]
 [0.68834559 0.80328455 0.65560904 0.89238025 0.58422885]
 [0.74772849 0.0101444  0.99932497 0.98620468 0.90154399]]


8.Creates 3X2 Array without Initializing the values

In [47]:
h=np.empty((3,2))
print(h)

[[1.9 2. ]
 [3.  4. ]
 [5.  6. ]]
