<a href="https://colab.research.google.com/github/KIRANRW9/Numpy/blob/repo-exercise/NumpyD5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Subsetting, Slicing, Boolean & Fancy Indexing
NumPy gives you powerful ways to access and manipulate parts of arrays.



#1. Subsetting (Indexing Single Elements)


In [ ]:
import numpy as np
a=np.array([1,2,3])
print("a[2]:",a[2])

b=np.array([[1,2,3],[4,5,6]])
print("b[1][2]=",b[1][2])
print("b[1,2]=",b[1,2])

a[2]: 3
b[1][2]= 6
b[1,2]= 6


#2. Slicing getting ranges of the data

In [ ]:
# Slice first two elements from 1D array
print("a[0:2]=",a[0:2])

# Get values from rows 0 and 1, column 1
print("b[0:2,1]=",b[0:2,1])

# Select all elements of row 0
print("b[:1]",b[:1])

#Reversing an array
print("a[::-1]=",a[::-1])


a[0:2]= [1 2]
b[0:2,1]= [2 5]
b[:1] [[1 2 3]]
a[::-1] [3 2 1]


#3. Using Ellipsis (...) for Multidimensional Arrays

In [ ]:
c=np.array([
    [[1,2,3],[4,5,6]],
    [[3,2,1],[4,5,6]]
])
# Select all elements from 2nd "big" row (c[1,:,:])
print("c1, ...]=\n\n",c[1, ...])

c1, ...]=

 [[3 2 1]
 [4 5 6]]


#4. Boolean Indexing


In [ ]:
print("a=",a)
print("a[a<=2]=",a[a<=2])

e=np.arange(1,21)
print("e=",e)
print("e[e&1==0]=",e[e&1==0])#Selecting only even numbers


a= [1 2 3]
a[a<=2]= [1 2]
e= [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
e[e&1==0]= [ 2  4  6  8 10 12 14 16 18 20]


#5. Fancy Indexing (Advanced Index Selection)

In [ ]:
#selecting specific elements using index pairs
d=np.array([[2.3,4.3,4.8],[6.7,2.1,8.2]])
print("d=\n",d)

result1=d[[1,0,1],[0,1,1]]
print("result1=\n",result1)



h = np.array([[1.5, 2.0, 3.0],
              [4.0, 5.0, 6.0]])


# Step 1: Select 4 rows (with repetition)
rows = h[[1, 0, 1, 0]]

# Step 2: From those rows, select columns 0, 1, 2, and 0
result2 = rows[:, [0, 1, 2, 0]]
print(result2)


result2 = h[[1, 0, 1, 0]][:, [0, 1, 2, 0]]
print(result2)

d=
 [[2.3 4.3 4.8]
 [6.7 2.1 8.2]]
result1=
 [6.7 4.3 2.1]
[[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]
[[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]
