<a href="https://colab.research.google.com/github/KIRANRW9/Numpy/blob/repo-exercise/NumpyD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Saving & Loading On Disk
np.save()

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
np.save("my_array",a)

np.savez()
Save multiple arrays into a single compressed file(.npz).




Arrays are saved with default names arr_0,arr_1,...


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[5,6,7,8],[9,10,11,12]])

np.savez("my_ar.npz",a,b)

np.load()

In [ ]:
loaded_array=np.load("my_array.npy")
print(loaded_array)

[1 2 3 4 5]


In [ ]:
loaded_array=np.load("my_ar.npz")
print(loaded_array)
print(loaded_array['arr_0'])
print("--------------------------------------")
print(loaded_array['arr_1'])

NpzFile 'my_ar.npz' with keys: arr_0, arr_1
[1 2 3 4]
--------------------------------------
[[ 5  6  7  8]
 [ 9 10 11 12]]


#Loads data from a text file into a NumPy array.

In [ ]:
import numpy as np
data=np.loadtxt("my_file.txt")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#Loads data from a CSV or text file, even if it has missing values.



In [ ]:
data=np.genfromtxt('my_files.csv',delimiter=',')
print(data)



[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]]


#Saves a NumPy array to a text file.



In [ ]:
a=np.array([1,2,3,4,5])
np.savetxt("Myarr.txt",a,delimiter=" ")
np.savetxt("Myarr1.txt",a,fmt='%d',delimiter=" ")

NumPy supports many different data types that help you store and manage data efficiently. Here are some common ones:


In [ ]:
import numpy as np
data=[
    np.array([1],dtype=np.int64),
    np.array([3.14],dtype=np.float32),
    np.array([1+2j],dtype=np.complex64),
    np.array([True],dtype=np.bool_),
    np.array(["Hello Kiran"],dtype=np.str_),
    np.array(["కిరణ్"],dtype=np.str_),
    np.array([[1,2],"Hello","కిరణ్"],np.object_),
    #np.array([1,2],dtype=np.void),
    #np.array([],dtype=np.void)

]

for item in data:
  print(item,"| Data type: ", item.dtype)

[1] | Data type:  int64
[3.14] | Data type:  float32
[1.+2.j] | Data type:  complex64
[ True] | Data type:  bool
['Hello Kiran'] | Data type:  <U11
['కిరణ్'] | Data type:  <U5
[list([1, 2]) 'Hello' 'కిరణ్'] | Data type:  object
