<a href="https://colab.research.google.com/github/KIRANRW9/Numpy/blob/repo-exercise/NumpyD6ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Transposing Arrays

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print("Orginal Array:a=\n",a)


#method 1
print("Transposed Array \n",a.transpose())
print(np.transpose(a))

#method 2
print(a.T)

Orginal Array:a=
 [[1 2 3]
 [4 5 6]]
Transposed Array 
 [[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


#2. Changing Array Shape
Flatten the array

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print("Orginal Array:\n",b)
flat=b.ravel()
print("Flatted Array:",flat)

Orginal Array:
 [[1 2 3]
 [4 5 6]]
Flatted Array: [1 2 3 4 5 6]


Reshape the array


In [ ]:
reshaped=b.reshape(3,2)
print("Reshaped Array:\n",reshaped)


Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


#3. Adding/Removing Elements
Resize array

In [ ]:
h=np.array([[1,2],[3,4]])
h.resize((2,4))
print(h)

[[1 2 3 4]
 [0 0 0 0]]


Append

In [ ]:
g=np.array([[5,6],[7,8]])
appendded=np.append(h,g)
print(appendded)

[1 2 3 4 0 0 0 0 5 6 7 8]


Insert



In [ ]:
a=np.array([1,2,3])
inserted=np.insert(a,1,99)
print(inserted)

[ 1 99  2  3]


Delete

In [ ]:
deleted=np.delete(a,[1])
print(deleted)

[1 3]


#4. Combining Arrays
Concatenate



In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
combined=np.concatenate((a,b),axis=0)
print("Concaatenated:",combined)

Concaatenated: [1 2 3 4 5 6]


Stack vertically

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1.5, 2.0, 3.0], [4.0, 5.0, 6.0]])
stacked_v=np.vstack((a,b))
print("Stacked vertically:\n", stacked_v)

Stacked vertically:
 [[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]


Stack horizontally

In [ ]:
e = np.array([[7., 7.], [7., 7.]])
f = np.array([[1., 0.], [0., 1.]])
stacked_h=np.hstack((e,f))
print("Stacked horizanally\n",stacked_h)

Stacked horizanally
 [[7. 7. 1. 0.]
 [7. 7. 0. 1.]]


Column-wise stacking


In [ ]:
a = np.array([1, 2, 3])
d = np.array([10, 15, 20])
col_stack1=np.column_stack((a,d))
col_stack2=np.c_[a,d]

print(col_stack1)
print(col_stack2)

[[ 1 10]
 [ 2 15]
 [ 3 20]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]


#5. Splitting Arrays
Horizontal split

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
split=np.hsplit(a,3)
print(split)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


Vertical split

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
split=np.vsplit(c,2)
print(split)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
c = np.array([
    [[1.5, 2.0, 1.0], [4.0, 5.0, 6.0]],
    [[3.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
])

split_v = np.vsplit(c, 2)
print("Vertically split:", split_v)


Vertically split: [array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
        [4., 5., 6.]]])]
