<a href="https://colab.research.google.com/github/KIRANRW9/Numpy/blob/repo-exercise/NumpyD4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Arithmatic operators

In [ ]:
import numpy as np
g=np.array([[2,3,4],[5,6,7]])
h=np.array([[2.1,3.5,2.2],[1.2,5.3,2]])

#Arithmatic opeerations
print("g+h\n",g+h)
print()
print(np.add(g,h))

print("h-g:\n",h-g)
print()
print(np.subtract(h,g))

print("g*h:\n",g*h)
print()
print(np.multiply(g,h))

print("g/h:\n",g/h)
print()
print(np.divide(g,h))

print("g//h:\n",g//h)
print()
print(np.floor_divide(g,h))


g+h
 [[ 4.1  6.5  6.2]
 [ 6.2 11.3  9. ]]

[[ 4.1  6.5  6.2]
 [ 6.2 11.3  9. ]]
h-g:
 [[ 0.1  0.5 -1.8]
 [-3.8 -0.7 -5. ]]

[[ 0.1  0.5 -1.8]
 [-3.8 -0.7 -5. ]]
g*h:
 [[ 4.2 10.5  8.8]
 [ 6.  31.8 14. ]]

[[ 4.2 10.5  8.8]
 [ 6.  31.8 14. ]]
g/h:
 [[0.95238095 0.85714286 1.81818182]
 [4.16666667 1.13207547 3.5       ]]

[[0.95238095 0.85714286 1.81818182]
 [4.16666667 1.13207547 3.5       ]]
g//h:
 [[0. 0. 1.]
 [4. 1. 3.]]

[[0. 0. 1.]
 [4. 1. 3.]]


#Math Functions

In [ ]:
a=np.arange(1,21)
print(a)
print()
print("Exponent",np.exp(a))
print()
print("Square Root",np.sqrt(a))
print()
print("sin(a)",np.sin(a))
print()
print("cos(a)",np.cos(a))
print()
print("log(a)",np.log(a))




e = np.array([[1, 2], [3, 4]])
f = np.array([[1, 1], [1, 1]])
x=np.dot(e,f)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Exponent [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08 4.85165195e+08]

Square Root [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595]

sin(a) [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721  0.91294525]

cos(a) [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0

#Aggregate Functions

In [ ]:
print("Sum:",np.sum(a))
print(a.sum())
print("Min",np.min(a))
print("Max:",np.max(a))
print("Mean:",np.mean(a))
print("Median",np.median(a))
print("Std:",np.std(a))
print("Var",np.var(a))
x=np.array([0,1])
print(np.cumsum(x))

Sum: 210
210
Min 1
Max: 20
Mean: 10.5
Median 10.5
Std: 5.766281297335398
Var 33.25
[0 1]


#a.view() → Creates a view (linked copy)
1.Copying Arrays in NumPy
When you work with arrays in NumPy, you sometimes want to create a new array that is either:

Connected to the original (called a "view")

Separate and independent (called a "copy")

In [ ]:
a=np.arange(1,9)
h=a.view()
h[[0,1]]=12,13
print(a)
print(h)

[12 13  3  4  5  6  7  8]
[12 13  3  4  5  6  7  8]


#🔹 a.copy() or np.copy(a) → Creates a deep copy
python
Copy
Edit


In [ ]:
x=a.copy()
y=np.copy(a)
y[[0,1]]=9,4
print(x)
print(y)

[12 13  3  4  5  6  7  8]
[9 4 3 4 5 6 7 8]


 2.Saving & Loading Arrays
 np.save('file', array) → saves to .npy file

In [ ]:
np.save("myar_a",x)

loaded=np.load("myar_a.npy")
print(loaded)

[12 13  3  4  5  6  7  8]


In [ ]:
#To save multiple arrays
np.savez("arrays.npz",x,y)
l1=np.load("arrays.npz")
print(l1['arr_0'])
print("______________")
print(l1['arr_1'])


[12 13  3  4  5  6  7  8]
______________
[9 4 3 4 5 6 7 8]


#Sorting

In [ ]:
c=np.array([[1,3,2],[8,7,9]])
print(c)
print()
c.sort(axis=1)#Row wise
print(c)

[[1 3 2]
 [8 7 9]]

[[1 2 3]
 [7 8 9]]


In [ ]:
c=np.array([[1,35,22],[81,7,9]])
print(c)
print()
c.sort(axis=0)#Column wise
print(c)

[[ 1 35 22]
 [81  7  9]]

[[ 1  7  9]
 [81 35 22]]
